### ISSUE TITLE
About pseudo code

### ISSUE THREAD

**Issue by DawnJYe** [Chumsy0725/FBC-SA#1]
In algorithm 1 pseudocode, is the step for weak augmentation missing in the code for generating pseudo labels?

**Comment by Chumsy0725** [comment]
@XiaojieGan Thank you for your interest in our work. 

Weak Augmentation is included when generating pseudo labels. I would like to point you to the DataLoader and the "parse_batch_train" function for more clarity.

**Comment by Chumsy0725** [comment]
@XiaojieGan Thank you for your interest in our work.

Weak Augmentation is included when generating pseudo labels. I would like to point you to the DataLoader and the "parse_batch_train" function for more clarity.

**Comment by DawnJYe** [comment]
Oh What I'm referring to is the pseudo-code in your paper, not the Python code; specifically, the process of generating pseudo labels in the 13th line of the pseudo-code.
