### ISSUE TITLE
About Feature-based Conformity

### ISSUE THREAD

**Issue by DawnJYe** [Chumsy0725/FBC-SA#2]
”the posterior from the same and different source domains in feature space, should align with its pseudo-label produced from the model’s output space”. I'm somewhat puzzled. Could you clarify why the alignment is set up like this? I'd appreciate your insights. Thank you！

**Comment by Chumsy0725** [comment]
Hi @XiaojieGan, Thank you for your interest in our work. So the data instances belonging to a specific class should be in a close range of each other in the feature space  (a cluster) regardless of the source domain the instances are coming from.
