### ISSUE TITLE
TerraIncognita dataset

### ISSUE THREAD

**Issue by sonhamin** [Chumsy0725/FBC-SA#3]
Thanks for the great work!

I was just wondering how you divided the domains for the TerraIncognita and DigitsDG dataset. 
I didn't see your paper mention this either.

**Comment by Chumsy0725** [comment]
Hi @sonhamin, Thank you for your interest in our work! Please see the following repos for dataset preparations. 

> Dassl [https://github.com/KaiyangZhou/Dassl.pytorch/tree/master](url)
> SSDG-Benchmark https://github.com/KaiyangZhou/ssdg-benchmark
